/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirapp;



import config.Koneksi;
import java.sql.PreparedStatement;
import java.sql.Connection;
import controller.GetData;
import models.Produk;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ACER
 */
public class APP extends javax.swing.JFrame {
    private int totalBelanja = 0;
    private List<Integer> selectedRowsList = new ArrayList<>();
    private boolean isEditing = false;

    private Connection Con;

     public void clear(){
        inpnama.setText("");
        inpHarga.setText("");
        inpJumlah.setText("");
        inpnama.requestFocus();
    }
    public  void insertData(){
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        int row = Tabel.getRowCount();
        model.addRow(new Object[]{
            row += 1,
            inpnama.getText(),
            inpHarga.getText(),
            inpJumlah.getText()
        });
    }
    public double hitungTotal(){
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        int rowCount = model.getRowCount();
        double total = 0.0;
        
        for(int i = 0; i < rowCount; i++){
            double harga = Double.parseDouble(model.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            total += harga*jumlah;
        }
        return total;
    }      
    /**
     * Creates new form APP
     */
    public APP() {
        initComponents();
        newTable();
    }
    private void newTable(){
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        model.setRowCount(0);

        List<Produk> dataList = GetData.readData();

        for (Produk data : dataList ) {
            Object[] row = {data.getId(), data.getName(), data.getPrice(), data.getStock()};
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inpnama = new javax.swing.JTextField();
        inpHarga = new javax.swing.JTextField();
        inpJumlah = new javax.swing.JTextField();
        ButTambah = new javax.swing.JButton();
        ButEdit = new javax.swing.JButton();
        ButDelete = new javax.swing.JButton();
        ButClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inpTotal = new javax.swing.JTextField();
        inpTunai = new javax.swing.JTextField();
        inpKembali = new javax.swing.JTextField();
        ButHitung = new javax.swing.JButton();
        ButSimpan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DB-MYSHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("HARGA");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("JUMLAH");

        inpnama.setBackground(new java.awt.Color(0, 0, 0));
        inpnama.setForeground(new java.awt.Color(255, 255, 255));
        inpnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpnamaActionPerformed(evt);
            }
        });

        inpHarga.setBackground(new java.awt.Color(0, 0, 0));
        inpHarga.setForeground(new java.awt.Color(255, 255, 255));
        inpHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHargaActionPerformed(evt);
            }
        });

        inpJumlah.setBackground(new java.awt.Color(0, 0, 0));
        inpJumlah.setForeground(new java.awt.Color(255, 255, 255));
        inpJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJumlahActionPerformed(evt);
            }
        });

        ButTambah.setBackground(new java.awt.Color(0, 255, 0));
        ButTambah.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButTambah.setText("Tambah");
        ButTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButTambahActionPerformed(evt);
            }
        });

        ButEdit.setBackground(new java.awt.Color(0, 51, 255));
        ButEdit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButEdit.setText("Edit");
        ButEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEditActionPerformed(evt);
            }
        });

        ButDelete.setBackground(new java.awt.Color(255, 255, 0));
        ButDelete.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButDelete.setText("Delete");
        ButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteActionPerformed(evt);
            }
        });

        ButClear.setBackground(new java.awt.Color(255, 0, 51));
        ButClear.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButClear.setText("Clear");
        ButClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClearActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setText("Tunai");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Kembali");

        inpTotal.setEditable(false);
        inpTotal.setBackground(new java.awt.Color(0, 0, 0));
        inpTotal.setForeground(new java.awt.Color(255, 255, 255));
        inpTotal.setText("Rp.");
        inpTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTotalActionPerformed(evt);
            }
        });

        inpTunai.setBackground(new java.awt.Color(0, 0, 0));
        inpTunai.setForeground(new java.awt.Color(255, 255, 255));
        inpTunai.setCaretColor(new java.awt.Color(255, 255, 255));
        inpTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTunaiActionPerformed(evt);
            }
        });

        inpKembali.setEditable(false);
        inpKembali.setBackground(new java.awt.Color(0, 0, 0));
        inpKembali.setForeground(new java.awt.Color(255, 255, 255));
        inpKembali.setText("Rp.");

        ButHitung.setBackground(new java.awt.Color(102, 102, 102));
        ButHitung.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButHitung.setText("Hitung");
        ButHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButHitungActionPerformed(evt);
            }
        });

        ButSimpan.setBackground(new java.awt.Color(102, 102, 102));
        ButSimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ButSimpan.setText("Simpan");
        ButSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(inpTunai)
                    .addComponent(inpKembali)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ButHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButSimpan)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inpTunai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inpKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSimpan)
                    .addComponent(ButHitung))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA", "HARGA", "JUMLAH"
            }
        ));
        Tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inpHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(inpJumlah)
                            .addComponent(inpnama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButClear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inpJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButTambah)
                            .addComponent(ButEdit)
                            .addComponent(ButDelete)
                            .addComponent(ButClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpnamaActionPerformed

    private void inpHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpHargaActionPerformed

    private void inpJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpJumlahActionPerformed

    private void ButTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButTambahActionPerformed
        // TODO add your handling code here:
         if(inpnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Barang Belum di Masukan");
        }else if(inpHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Barang Belum di Masukan");
        }else if(inpJumlah.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Barang Belum di Masukan");
        }else{
            insertData();
            clear();
            
            double total = hitungTotal();
            inpTotal.setText("Rp." + String.valueOf(total));
        }

       
    }//GEN-LAST:event_ButTambahActionPerformed

    private void ButEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
        int rowSelect = Tabel.getSelectedRow();
        
        if(ButEdit.getText().equals("Edit")){
            ButTambah.setEnabled(false);
            ButDelete.setEnabled(false);
            ButEdit.setText("Update");
            inpnama.setText(model.getValueAt(rowSelect, 1).toString());
            inpHarga.setText(model.getValueAt(rowSelect, 2).toString());
            inpJumlah.setText(model.getValueAt(rowSelect, 3).toString());
        }else {
            ButTambah.setEnabled(true);
            ButDelete.setEnabled(true);
            ButEdit.setText("Edit");
            
            String namabarang = inpnama.getText();
            String hargabarang = inpHarga.getText();
            String jumlahbarang = inpJumlah.getText();
            
            model.setValueAt(namabarang, rowSelect, 1);
            model.setValueAt(hargabarang, rowSelect, 2);
            model.setValueAt(jumlahbarang, rowSelect, 3);
        }

        
    }//GEN-LAST:event_ButEditActionPerformed

    private void ButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = Tabel.getSelectedRow();
        
        if (selectedRow != -1){
            int id = (int) Tabel.getValueAt(selectedRow, 0);
            GetData.deleteData(id);
            newTable();
        } else {
        JOptionPane.showMessageDialog(null, "Belum Ada Data Terpilih");
        }
//        DefaultTableModel model = (DefaultTableModel) Tabel.getModel();
//        int rowSelect = Tabel.getSelectedRow();
//        
//        if(rowSelect == -1){
//            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.",
//                    "Error", JOptionPane.ERROR_MESSAGE);
//        } else {
//            
//          int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin menghapus data ini?", 
//                  "Konfirmasi Pengahapusan Data",JOptionPane.YES_NO_OPTION);
//          if(confirm == JOptionPane.YES_OPTION){
//              model.removeRow(rowSelect);
//          }
//        }
//        connection();
//        query = "DELETE FROM produk WHERE nama=?";
//        try {
//            preparedStatement = Con.prepareStatement(query);
//            preparedStatement.setString(1, inpnama.getText());
//            preparedStatement.executeUpdate();
//          
//            preparedStatement.close();           
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
        
    }//GEN-LAST:event_ButDeleteActionPerformed

    private void ButClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClearActionPerformed
        // TODO add your handling code here:
        clear();
        inpTotal.setText("Rp.");
        inpTunai.setText("0");
        inpKembali.setText("Rp.");
        
        newTable();     
    }//GEN-LAST:event_ButClearActionPerformed

    private void inpTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTunaiActionPerformed

    private void ButHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButHitungActionPerformed
        // TODO add your handling code here:
        try {
        double jumlahBayar = Double.parseDouble(inpTunai.getText());
        double total = hitungTotal();
        
        if (jumlahBayar < total) {
            double kurang = total - jumlahBayar;
            JOptionPane.showMessageDialog(this, "Uang anda kurang Rp." + kurang, "Peringatan", JOptionPane.WARNING_MESSAGE);
        }else {
            double kembalian = jumlahBayar - total;
            inpKembali.setText("Rp." + String.valueOf(kembalian));
        }

    } catch (NumberFormatException e) {
        // Penanganan kesalahan jika input tidak valid
        JOptionPane.showMessageDialog(this, "Jumlah bayar tidak valid. Mohon masukkan angka yang benar.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
//        double jumlahBayar = Double.parseDouble(inpTunai.getText());
//        double total = hitungTotal();
//        double kembalian = jumlahBayar - total;
//        inpTotal.setText("Rp." + String.valueOf(total));
//        inpKembali.setText("Rp." + String.valueOf(kembalian));
       
    }//GEN-LAST:event_ButHitungActionPerformed

    private void ButSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSimpanActionPerformed
        // TODO add your handling code here:
//            int selectedRow = Tabel.getSelectedRow();
//
//        if (selectedRow != -1) {
//            if (!selectedRowsList.contains(selectedRow)) {
//                selectedRowsList.add(selectedRow);
//            }
//
//            int stockBarang = Integer.parseInt(Tabel.getValueAt(selectedRow, 2).toString());
//
//            if (stockBarang > 0) {
//                double hargaBarang = Double.parseDouble(Tabel.getValueAt(selectedRow, 4).toString());
//                totalBelanja += hargaBarang;
//                inpTotal.setText(String.valueOf(totalBelanja));
//
//                int jumlahBarang = Integer.parseInt(Tabel.getValueAt(selectedRow, 3).toString());
//                stockBarang--;
//                jumlahBarang++;
//                Tabel.setValueAt(stockBarang, selectedRow, 2);
//                Tabel.setValueAt(jumlahBarang, selectedRow, 3);
//            }
//        } else {
//        JOptionPane.showMessageDialog(null, "Belum Ada Data Terpilih");
//        }
        try{
//            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_myshop","root","");

            Connection Con = Koneksi.connection();
            int rowCount = Tabel.getRowCount();
            for(int i = 0; i < rowCount; i++){
               String Column1 = Tabel.getValueAt(i, 1).toString();
               String Column2 = Tabel.getValueAt(i, 2).toString();
               String Column3 = Tabel.getValueAt(i, 3).toString();
               
               String sql = "INSERT INTO produk (NAMA, HARGA, JUMLAH) VALUES (?,?,?)";
               PreparedStatement statement = Con.prepareStatement(sql);
               
               statement.setString(1, Column1);
               statement.setString(2, Column2);
               statement.setString(3, Column3);
               
               statement.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");
            Con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data ke database.");    
        }
    }//GEN-LAST:event_ButSimpanActionPerformed

    private void TabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelAncestorAdded

    private void inpTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButClear;
    private javax.swing.JButton ButDelete;
    private javax.swing.JButton ButEdit;
    private javax.swing.JButton ButHitung;
    private javax.swing.JButton ButSimpan;
    private javax.swing.JButton ButTambah;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField inpHarga;
    private javax.swing.JTextField inpJumlah;
    private javax.swing.JTextField inpKembali;
    private javax.swing.JTextField inpTotal;
    private javax.swing.JTextField inpTunai;
    private javax.swing.JTextField inpnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables


}
